spring.application.name=logistic_fleet
spring.jpa.database=postgresql
spring.jpa.show-sql=false
spring.jpa.hibernate.ddl-auto=none

spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5432/logistics_fleet_db
spring.datasource.username=postgres
spring.datasource.password=JDM_RaspBerryPi68